//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreederHub.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class breederhubEntities : DbContext
    {
        public breederhubEntities()
            : base("name=breederhubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breed> Breeds { get; set; }
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<Litter> Litters { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
    }
}
