//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreederHub.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        public Dog()
        {
            this.Litters = new HashSet<Litter>();
            this.Litters1 = new HashSet<Litter>();
            this.Litters2 = new HashSet<Litter>();
        }
    
        public int DogId { get; set; }
        public int Breed_FK { get; set; }
        public System.DateTime DOB { get; set; }
        public string Name { get; set; }
        public string KCNumber { get; set; }
        public string Gender { get; set; }
        public int Owner_FK { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual ICollection<Litter> Litters { get; set; }
        public virtual ICollection<Litter> Litters1 { get; set; }
        public virtual ICollection<Litter> Litters2 { get; set; }
    }
}
