//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreederHub.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorId { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorMessage { get; set; }
        public string PageName { get; set; }
        public string User_FK { get; set; }
        public string PageUrl { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual ErrorLog ErrorLogs1 { get; set; }
        public virtual ErrorLog ErrorLog1 { get; set; }
    }
}
